name: svc

on:
  push:
    branches:
      - svc

permissions:
  contents: write
  discussions: write

env:
  DOCKER_IMAGE: svc
  DOCKER_CONTAINER: svc

jobs:
  build:
    name: Generate License
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      id: build
      run: |
        source .env
        rm -rf crack
        mkdir crack
        echo "ELASTIC_VERSION=${ELASTIC_VERSION}"
        echo "TAGNAME=${ELASTIC_VERSION}-$(git rev-parse --short HEAD)-cracked" >> $GITHUB_OUTPUT

        docker build --build-arg ELASTIC_VERSION=${ELASTIC_VERSION} -t $DOCKER_IMAGE svc
        docker run --rm -v ${PWD}/crack:/crack/output --name $DOCKER_CONTAINER $DOCKER_IMAGE bash build_crack_jar.sh

    - uses: actions/github-script@v7
      id: push-tag
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{ steps.build.outputs.TAGNAME }}',
            sha: context.sha
          })
    
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.build.outputs.TAGNAME }}
        